language: php

os: linux
dist: jammy

env:
  - XDEBUG_MODE=coverage

php:
  - 8.3

install:
  - composer install --no-progress --no-interaction --no-suggest

script:
  - ./vendor/bin/phpunit --no-progress --coverage-clover build/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
